### ISSUE TITLE
Remaining Issues for MLP performance on par with libxsmm-dnn

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#783]
These are the known issues to reach libxsmm-dnn performance on "pre-packed layer" MLPs:
- [ ] Single allocation on page boundary (see #777)
- [ ] Beta=Zero (see #777)
- [ ] XSMM fusion (see #752)
- [ ] Pass loop order to libxsmm brgemm calls

In theory, if we get all of those in, it should reach parity. If more is discovered, please add to the list. Let's only close this issue when we reach parity on the base MLP benchmarks we have for pre-packed MLPs.

@chelini @alheinecke

**Comment by rengolin** [comment]
Beta=0 is done, benchmark IR is affected, but we got <1% performance change from that, probably within noise. We didn't expect a huge change, so not a big deal.
